export const USERS_UPDATE = 'USERS_UPDATE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_DETAIL_UPDATE = 'USER_DETAIL_UPDATE';
export const TRANSFER_EXECUTED = 'TRANSFER_EXECUTED';
export const TRANSFER_ERROR = 'TRANSFER_ERROR';
export const RESET_ERROR = 'RESET_ERROR';